src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length:32)]
    private ?string $name = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private ?bool $is_active = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable:true)]
    private ?\DateTimeInterface $modified_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeInterface
    {
        return $this->modified_at;
    }

    public function setModifiedAt(?\DateTimeInterface $modified_at): static
    {
        $this->modified_at = $modified_at;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Üdv!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
            <link href="{{ asset('css/style.css') }}" type="text/css" rel="stylesheet" />
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bejelentkezés{% endblock %}

{% block body %}
    {{ form_start(form)}}
    <div class="col-lg-6 offset-lg-3">

        <div class="mb-3 row">
            <div class="col-md-12 text-center">
                <h2>Bejelentkezés</h2>
            </div>
        </div>

        <div class="mb-4 row">
            {% for label, messages in app.flashes(['error', 'success']) %}
                {% for message in messages %}
                    <div class="confirmation-container col-md-12 text-center">
                        {% if label == "error" %}
                            <span class="error">{{ message }}</span>
                        {% endif %}
                    </div>
                {% endfor %}
            {% endfor %}
        </div>

        <div class="mb-4 row">
            <div class="col-md-6 offset-md-3">
                {{ form_errors(form) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-4 offset-md-4">
                {{ form_row(form._username) }}
            </div>
        </div>
        <div class="mb-4 row">
            <div class="col-md-4 offset-md-4">
                {{ form_row(form._password) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-12 text-center">
                {{ form_row(form.submit) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-12 text-center">
                <a href="/happyMed/public/index.php/registration" class="btn btn-secondary">Regisztráció</a>
            </div>
        </div>

    </div>
    {{ form_end(form) }}
{% endblock %}

templates/registration.html.twig
{% extends 'base.html.twig' %}

{% block title %}Regisztráció{% endblock %}

{% block body %}
    {{ form_start(form)}}
    <div class="col-lg-6 offset-lg-3">

        <div class="mb-3 row">
            <div class="col-md-12 text-center admin-line">
                <h2 class="floating-title-2">Regisztráció</h2>
                <a href="/happyMed/public/index.php/login" class="btn btn-primary floating-button">Vissza</a>
            </div>
        </div>

        <div class="mb-3 row">
            <div class="col-md-12 text-center">
                <h3>Új felhasználó regisztrálása</h3>
            </div>
        </div>

        <div class="mb-4 row">
            {% for label, messages in app.flashes(['error', 'success']) %}
                {% for message in messages %}
                    <div class="confirmation-container col-md-12 text-center">
                        {% if label == "success" %}
                            <span class="confirmation">{{ message }}</span>
                        {% else %}
                            <span class="error">{{ message }}</span>
                        {% endif %}
                    </div>
                {% endfor %}
            {% endfor %}
        </div>

        <div class="mb-4 row">
            <div class="col-md-4 offset-md-4">
                {{ form_row(form.name) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-4 offset-md-4">
                {{ form_row(form.email) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-4 offset-md-4">
                {{ form_row(form.password) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-12 text-center">
                {{ form_row(form.submit) }}
            </div>
        </div>

    </div>
    {{ form_end(form) }}
{% endblock %}

templates/user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Belépve{% endblock %}

{% block body %}
    <div class="col-lg-6 offset-lg-3">

        <div class="mb-3 row">
            <div class="col-md-12 text-center admin-line">
                <h2 class="floating-title">Admin felület</h2>
                <a href="/happyMed/public/index.php/logout" class="btn btn-primary floating-button">Kijelentkezés</a>
            </div>
        </div>

        <div class="mb-3 row">
            <div class="col-md-12 text-center">
                <h3>Felhasználók</h3>
            </div>
        </div>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>Id</th>
                <th>Név</th>
                <th>E-mail cím</th>
                <th>Státusz</th>
                <th>Létrehozás dátuma</th>
            </tr>
            </thead>
            <tbody>
            {% for item in form %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.email }}</td>
                    {% if item.isActive == true %}
                        <td>Aktív</td>
                    {% else %}
                        <td>Inaktív</td>
                    {% endif %}
                    <td>{{ item.createdAt|date('Y-m-d H:i:s') }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}